services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      CORS_ORIGINS: '["http://localhost:8080"]'

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
